Ssttp 1068
hmrc/self-service-time-to-pay-frontend pull request #197
Opened 2017-02-14 15:27 UTC by nkaraolis

Added due date and amount page as well as added test coverage

2017-02-14 16:39 UTC, Smudgey requested changes

2017-02-14 16:39 UTC, Smudgey commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/CalculatorController.scala
> +      case Some(TTPSubmission(_, _, _, _, Some(EligibilityTypeOfTax(true, false)), Some(EligibilityExistingTTP(Some(false))), _, _, _, _)) =>
We need to look at possibly setting the date to None on this page load due to navigational issues

2017-02-14 16:39 UTC, Smudgey commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/CalculatorController.scala
> +      case Some(ttpData@TTPSubmission(_, _, _, _, _, _, _, _, _, _)) =>
Do a check on whether user is valid otherwise they could postman this? This seems very minor though will discuss further

2017-02-14 16:39 UTC, Smudgey commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/CalculatorController.scala
> +      case Some(ttpData@TTPSubmission(_, _, _, _, _, _, CalculatorInput(debits, _, _, _, _, _), _, _, Some(debtDate))) =>
Nick says rename to debitDate instead of debtDate

2017-02-14 16:39 UTC, Smudgey commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/CalculatorController.scala
> +        val minimumPaymentAmount = 32
Possibly rename to something better

2017-02-15 08:22 UTC, nkaraolis commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/CalculatorController.scala
> +        val minimumPaymentAmount = 32
Renamed

2017-02-15 08:23 UTC, nkaraolis commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/CalculatorController.scala
> +      case Some(ttpData@TTPSubmission(_, _, _, _, _, _, _, _, _, _)) =>
Added check for None on the date

2017-02-15 09:27 UTC, Smudgey approved these changes

2017-02-15 09:29 UTC, merged