Convert data model
hmrc/self-service-time-to-pay-frontend pull request #2
Opened 2016-10-25 14:00 UTC by MarkPaxton

2016-10-26 09:48 UTC, MarkPaxton commented
This incorporates PR #1 and I have changed the namespace to uk.gov.hmrc.ssttp.

2016-10-31 07:37 UTC, nedda76 requested changes

2016-10-31 07:37 UTC, nedda76 commented on app/models/EligibilityDebtType.scala
> +}
Our flow for non-logged in journey no longer includes eligibility  - so the debtType and existingTtp models can be removed.

2016-10-31 07:37 UTC, nedda76 commented on app/models/EligibilityExistingTTP.scala
> +
same as above - can be removed, no longer part of the flow.

2016-10-31 07:37 UTC, nedda76 commented on conf/app.routes
> +POST   /eligibility/existing-ttp        controllers.EligibilityController.existingTtpSubmit()
All the eligibility routes, models, controllers and pages should be removed as they are no longer part of the non-logged in journey flow.

2016-10-31 07:37 UTC, nedda76 commented on test/models/EligibilityExistingTTP.scala
> +}
The specs for these can be removed as well - eligibility related.

2016-10-31 11:00 UTC, merged