SSTTP-1150
hmrc/self-service-time-to-pay-frontend pull request #221
Opened 2017-03-10 09:26 UTC by cavster

Changed Instalment  summary page and changed section to have no padding in css and updated print message

2017-03-10 15:05 UTC, Smudgey requested changes
The layout of the page doesn't quite match the prototype.

The details drop down section is underlined when it shouldn't be. There is a grey bar to the left of the text this details section opens that is also missing.

There needs a bit more space between the details section and the grey bullet point block of text at the bottom.

Whilst not introduced in this PR, There is a minor error in the text at the bottom, in the following text there is a comma after the word plan. This needs to be removed.

"If the interest rate changes during your instalment plan, we’ll settle the amount of interest you owe in your final payment."

2017-03-13 15:35 UTC, Smudgey commented
There is a big space at the top of the Instalment Summary page between the header and the start of the payment schedule.

The application complete page does not match up with the prototype. There is text missing from the green box at the top, text under 'What happens next?' is different and the green button text is incorrect.

![appl_comp_1154](https://cloud.githubusercontent.com/assets/7337624/23861688/b114c216-0802-11e7-9f44-42fa087e96e9.png)

2017-03-14 10:14 UTC, nkaraolis commented
Green button text is still incorrect
What happens next? heading is too big compared the prototype
Text under what happens next is still incorrect

2017-03-16 11:54 UTC, nkaraolis commented
Green button text still incorrect and there are merge conflicts but heading text is all good now

2017-03-17 11:21 UTC, nkaraolis commented
All code looks okay now, just run a quick imports optimisation when you fix the merge conflicts

2017-03-17 12:29 UTC, nkaraolis requested changes
Read code comments relating to merge errors and print button

2017-03-17 12:29 UTC, nkaraolis commented on conf/messages
> +<<<<<<< HEAD
The merge has left in the conflict lines and as such has stopped the branch from compiling so these will need removing as well adding in loads of duplicated messages

2017-03-17 12:29 UTC, nkaraolis commented on app/views/selfservicetimetopay/arrangement/application_complete.scala.html
>        <button onclick="window.print()" class="js-visible no-print button--secondary js-visible trackedPrintLink openOnPrint">@Messages("ssttp.arrangement.complete.print")</button>
Do we need the window.print()? The button just needs to be a dropdown to display the hidden data so this might not be necessary

2017-03-17 13:13 UTC, cavster commented on app/views/selfservicetimetopay/arrangement/application_complete.scala.html
>        <button onclick="window.print()" class="js-visible no-print button--secondary js-visible trackedPrintLink openOnPrint">@Messages("ssttp.arrangement.complete.print")</button>
That button is for printing the page ;)

2017-03-17 14:36 UTC, nkaraolis approved these changes

2017-03-17 14:49 UTC, Smudgey requested changes

2017-03-17 14:49 UTC, Smudgey commented on app/views/selfservicetimetopay/arrangement/application_complete.scala.html
> +        <summary style="width: 200px" class = "button button--secondary gutter-left">@Messages("ssttp.arrangement.complete.payment-details.summary")</summary>
This should be extracted to the ssttp css file

2017-03-17 14:49 UTC, Smudgey commented on conf/messages
> +ssttp.direct-debit.guarantee.list.4=If you receive a refund you are not entitled to, ssttp.arrangement.instalment-summary.printly contacting your bank or building society. Written confirmation may be
This line contains ssttp.arrangement.instalment-summary within the text message? Should the direct-debit guarantee even be changing? list.5 seems to have been deleted

2017-03-17 16:26 UTC, nkaraolis requested changes

2017-03-17 16:26 UTC, nkaraolis commented on conf/messages
>  ssttp.direct-debit.guarantee.list.4=If you receive a refund you are not entitled to, ssttp.arrangement.instalment-summary.printly contacting your bank or building society. Written confirmation may be
The text for this message doesn't match the prototype

2017-03-17 16:26 UTC, nkaraolis commented on public/css/self-service-time-to-pay.css
> +.ssttp-summary{
Is this empty class needed?

2017-03-17 16:29 UTC, cavster commented on public/css/self-service-time-to-pay.css
> +.ssttp-summary{
Yes

2017-03-17 16:48 UTC, nkaraolis approved these changes

2017-03-17 16:49 UTC, merged