Colm/ssttp 1151/change enter your bank details page
hmrc/self-service-time-to-pay-frontend pull request #226
Opened 2017-03-15 14:44 UTC by cavster

[https://jira.tools.tax.service.gov.uk/browse/SSTTP-1151](https://jira.tools.tax.service.gov.uk/browse/SSTTP-1151)

2017-03-16 16:05 UTC, nkaraolis requested changes
See comments:
Also, the errors for sort code and account number need to only have one error rather than both when a user doesn't input any data. Need to confirm this with design team though

2017-03-16 16:05 UTC, nkaraolis commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/DirectDebitController.scala
> +    val errorsNoDubs = form.errors.foldLeft[Seq[FormError]](Nil) { (acc, r) => {
Can we rename this to something a bit clearer?

2017-03-16 16:05 UTC, nkaraolis commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/DirectDebitController.scala
> +                    "accountNumber" -> validFormData.accountNumber, "sortCode1" -> sc1, "sortCode2" -> sc1, "sortCode3" -> sc1)),
This copies the value from the first box into every box. I guess you want to use sc2 and sc3 here for the other boxes?

2017-03-16 16:21 UTC, cavster commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/DirectDebitController.scala
> +    val errorsNoDubs = form.errors.foldLeft[Seq[FormError]](Nil) { (acc, r) => {
remove duplicated errors?

2017-03-16 16:23 UTC, nkaraolis commented on app/uk/gov/hmrc/selfservicetimetopay/controllers/DirectDebitController.scala
> +    val errorsNoDubs = form.errors.foldLeft[Seq[FormError]](Nil) { (acc, r) => {
Something like that should be okay

2017-03-17 10:47 UTC, nkaraolis commented
Correct values are now being put back in however, the error messages are slightly off.
If there is no data inputted in either the sort code and account number fields only need to show once message which should be depending on the form field:
Enter a sort code or Enter an account number

2017-03-17 12:09 UTC, nkaraolis commented
Everything looks good now, just optimise the imports when you resolve the conflicts :D

2017-03-17 13:58 UTC, nkaraolis approved these changes

2017-03-17 13:59 UTC, merged